name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to FTP server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.2
      with:
        server: ftp.zwemclubwoluwe.be
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        retries: 3
